version: '3.8'

services:
  server:
    build: ./server
    container_name: otc_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm run dev"

  client:
    build: ./client
    container_name: otc_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:16
    container_name: otc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otc_social_network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
